{% set name = "mols2grid" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mols2grid-{{ version }}.tar.gz
  sha256: 9956e2f45c3b0ed68e7c12b58628fb1ea15c684e218551bc81c6ddf2b48e550b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder >=0.8.1
  run:
    - jinja2 >=2.11.0
    - numpy
    - pandas
    - python >={{ python_min }}
    - rdkit >=2020.03.1
    - ipywidgets >=7,<8

test:
  imports:
    - mols2grid
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/nbextensions/mols2grid/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/mols2grid/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/mols2grid/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\mols2grid\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\mols2grid\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\mols2grid\\package.json (exit 1)          # [win]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cbouy/mols2grid
  summary: Interactive molecule viewer for 2D structures
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mols2grid.readthedocs.io
  dev_url: https://github.com/cbouy/mols2grid

extra:
  recipe-maintainers:
    - cbouy
    - hadim
