{% set name = "mols2grid" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mols2grid-{{ version }}.tar.gz
  sha256: 8401ca3bc70bcf5c7f7354564f94b76d0ed8ab098d5bb32870f65d1ad232c723

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder >=0.8.1
  run:
    - jinja2 >=2.11.0
    - numpy
    - pandas
    - python >={{ python_min }}
    - rdkit >=2020.03.1
    - anywidget

test:
  imports:
    - mols2grid
    - mols2grid.datafiles
  commands:
    - pip check
    - python -c 'from importlib.metadata import version; assert version("mols2grid") == "{{ version }}"'
    - python -c 'from importlib.resources import files; assert files("mols2grid").joinpath("static", "widget.js").exists()'
    - python -c 'from importlib.resources import files; assert files("mols2grid").joinpath("templates", "js", "callbacks", "show_3d.js").exists()'
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cbouy/mols2grid
  summary: Interactive molecule viewer for 2D structures
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mols2grid.readthedocs.io
  dev_url: https://github.com/cbouy/mols2grid

extra:
  recipe-maintainers:
    - cbouy
