{% set name = "mols2grid" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mols2grid-{{ version }}.tar.gz
  sha256: f50cd3c25766212146e92683a00f13ce06bb18a62b76848cddf5b385b08f7837

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jinja2 >=2.11.0
    - numpy
    - pandas
    - python >=3.7
    - rdkit >=2020.03.1
    - ipywidgets >=7,<8

test:
  imports:
    - mols2grid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cbouy/mols2grid
  summary: Interactive molecule viewer for 2D structures
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mols2grid.readthedocs.io
  dev_url: https://github.com/cbouy/mols2grid

extra:
  recipe-maintainers:
    - cbouy
    - hadim
